DROP SEQUENCE LOJA_SEQ;

DROP SEQUENCE CLIENTE_SEQ;

DROP SEQUENCE FUNCIONARIO_SEQ;

DROP SEQUENCE PRODUTO_SEQ;

DROP SEQUENCE VENDA_SEQ;

DROP SEQUENCE MARCA_SEQ;

DROP SEQUENCE SETOR_SEQ;

DROP TABLE VENDA;

DROP TABLE PRODUTO;

DROP TABLE MARCA;

DROP TABLE SETOR;

DROP TABLE FUNCIONARIO;

DROP TABLE CLIENTE;

DROP TABLE LOJA;

CREATE SEQUENCE FUNCIONARIO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE LOJA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE CLIENTE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;  

CREATE SEQUENCE PRODUTO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE VENDA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE MARCA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE SETOR_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE FUNCIONARIO
(
	ID               INT          NOT NULL PRIMARY KEY,
	NOME             VARCHAR(90)  NOT NULL,
	DATA_NASCIMENTO  DATE         NOT NULL,
	TELEFONE         DECIMAL(11)  NOT NULL,
	EMAIL            VARCHAR(100) NULL,
    SENHA            VARCHAR(15)  NOT NULL,
	CPF              DECIMAL(11)  NOT NULL,
	ENDERECO         VARCHAR(300) NOT NULL,
	FLGERENTE        CHAR(1)      NOT NULL,
	ID_LOJA          INT          NOT NULL
);

CREATE TABLE LOJA
(
	ID               INT          NOT NULL PRIMARY KEY,
	NOME             VARCHAR(90)  NOT NULL,
	TELEFONE         DECIMAL(11)  NOT NULL,
	EMAIL            VARCHAR(100) NULL,
	CNPJ             DECIMAL(14)  NOT NULL,
	ENDERECO         VARCHAR(300) NOT NULL             
);

CREATE TABLE CLIENTE
(
	ID               INT          NOT NULL PRIMARY KEY,
	NOME             VARCHAR(90)  NOT NULL,
	DATA_NASCIMENTO  DATE         NOT NULL,
	TELEFONE         DECIMAL(11)  NOT NULL,
	EMAIL            VARCHAR(100) NULL,
    SENHA            VARCHAR(15)  NOT NULL,
	CPF              DECIMAL(11)  NOT NULL,
	ENDERECO         VARCHAR(300) NOT NULL
);

CREATE TABLE MARCA
(
	ID                 INT          NOT NULL PRIMARY KEY,
	NOME          VARCHAR(90)  NOT NULL
);	

CREATE TABLE SETOR
(
	ID                 INT          NOT NULL PRIMARY KEY,
	NOME          VARCHAR(90)  NOT NULL
);	


CREATE TABLE PRODUTO
(
	ID                 INT          NOT NULL PRIMARY KEY,
	NOME               VARCHAR(90)  NOT NULL,
	DESCRICAO          VARCHAR(90)  NOT NULL,
	DATAVALIDADE       DATE   NOT NULL,
	MARCA              VARCHAR(90)  NOT NULL,
	ID_LOJA            INT          NOT NULL,
	ID_MARCA           INT          NOT NULL,
	ID_SETOR           INT          NOT NULL,
	CONSTRAINT  PRODUTO_LOJA_FK 
                FOREIGN KEY (ID_LOJA) 
                REFERENCES LOJA(ID),
    CONSTRAINT  PRODUTO_MARCA_FK 
                FOREIGN KEY (ID_MARCA) 
                REFERENCES MARCA(ID),
    CONSTRAINT  PRODUTO_SETOR_FK 
                FOREIGN KEY (ID_SETOR) 
                REFERENCES SETOR(ID)
);

CREATE TABLE VENDA
(
	ID                 INT          NOT NULL PRIMARY KEY,
	DESCRICAO          VARCHAR(90)  NOT NULL,
	QUANTIDADEPRODUTO  VARCHAR(90)  NOT NULL,
	VALOR              DECIMAL(8,2) NOT NULL,
	DATA               DATE    NOT NULL,
	NOTAFISCAL         INT          NOT NULL,
	ID_PRODUTO         INT          NOT NULL,
	ID_CLIENTE         INT          NOT NULL,
	CONSTRAINT  VENDA_PRODUTO_FK 
                FOREIGN KEY (ID_PRODUTO) 
                REFERENCES PRODUTO(ID),
    CONSTRAINT  VENDA_CLIENTE_FK 
                FOREIGN KEY (ID_CLIENTE) 
                REFERENCES CLIENTE(ID)
);

	
	
	
	
	
	
	
	
	